name: nucMACC
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
## bioconda packages
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.9
  - bioconda::bowtie2=2.4.4
  - bioconda::samtools=1.9
  - bioconda::deeptools=3.5.1
  - bioconda::ucsc-wigtobigwig=377
